alias commit='f() { git add . && git commit -m "$1" && git push };f'
alias temp='echo "$(($(cat /sys/devices/pci0000:00/*/hwmon/hwmon1/temp1_input) / 1000))°C"'
alias tempmonitor='while true; do; temp; sleep 1; done'
alias gpumonitor='while true; do; sensors | grep 'junction:' && sensors | grep 'fan1:'; sleep 1; done'
alias ~='cd ~'
